### ISSUE TITLE
Question: disabling graphs

### ISSUE THREAD

**Issue by rstacruz** [twada/power-assert#18]
Is it possible to disable it? In this example, I'd like to see the first and third parts, just not the second part.

```
  assert(this.ary.indexOf(zero) === two)
```

```
              |   |       |     |   |
              |   |       |     |   2
              |   -1      0     false
              [1,2,3]
```

```
  [number] two
  => 2
  [number] this.ary.indexOf(zero)
  => -1
```

**Comment by twada** [comment]
Hi @rstacruz, thank you for your question!

> I'd like to see the first and third parts, just not the second part.

Yes. you can suppress graphs by using [CUSTOMIZATION API](https://github.com/twada/power-assert#customization-api). Here is the example in this case.

```javascript
var assert = require('power-assert').customize({
    output: {
        renderers: [
            './built-in/file',
            './built-in/assertion',
            './built-in/binary-expression'
        ]
    }
});

describe('Array#indexOf()', function () {
    beforeEach(function () {
        this.ary = [1,2,3];
    });
    it('should return index when the value is present', function () {
        var zero = 0, two = 2;
        assert(this.ary.indexOf(zero) === two);
    });
});
```

output: 

```
  Array#indexOf()
    1) should return index when the value is present


  0 passing (16ms)
  1 failing

  1) Array#indexOf() should return index when the value is present:

        # /path/to/test/power_assert/mocha_power_assert_test.js:17

  assert(this.ary.indexOf(zero) === two)

  [number] two
  => 2
  [number] this.ary.indexOf(zero)
  => -1
```

Thanks!

**Comment by rstacruz** [comment]
I've actually tried doing that, but the actual line (`assert(this.ary.indexOf(zero) === two)`) isn't shown anymore.

**Comment by twada** [comment]
> but the actual line (assert(this.ary.indexOf(zero) === two)) isn't shown anymore.

Hmm, something is wrong...

I've created a [gist for this example](https://gist.github.com/twada/63aec6dfad028ab1baac), hope this can help you.

And if you show me your code on github or gist, I think I can help you.

**Comment by rstacruz** [comment]
ah! oops, my bad, it actually works >_<

Just in case, here's my gist: https://gist.github.com/rstacruz/f2fb7214d907aad1c250
